server {
    listen 80;
    server_name bastiongateway.com www.bastiongateway.com;
    root /opt/bastion-gateway/site;
    index index.html;
    location / {
        try_files $uri $uri/ =404;
    }
    location /api/ {
        proxy_pass http://127.0.0.1:8322;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
